roles:
  app:
    servers:
      webapp01.example.com.vagrant
      webapp02.example.com.vagrant
    options:
      ssh_access_via: gateway.example.com.vagrant
      ssh_key: id_rsa.2
  web:
    servers:
      dms01.example.com.vagrant

servers:
  DEFAULT:
    ssh_access_via:
  gateway.nowt.vagrant:
    ssh_access_via:
